name: CI Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches: 
      - master
jobs:
  SwiftLint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: SwiftLint
        uses: norio-nomura/action-swiftlint@3.1.0
  Build:
    name: Build
    runs-on: macOS-latest
    steps:
    - name: Checkout project
      uses: actions/checkout@v1
    - name: Bundle Install
      run: bundle install
    - name: Pod Install
      run: pod install
    - name: Build and Test
      run: |
        fastlane scan
